name: CI/CD Pipeline

on:
    push:
        tags:
          - "v*.*.*"
        branches:
            master

# Permission
permissions:
    contents: write

# Jobs to run
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Release
            uses: softprops/action-gh-release@v2
            if: startsWith(github.ref, 'refs/tags/')
            with:
                files: |
                    Release.txt
                    LICENSE
                make_latest: true
                body_path: CHANGELOG.md